apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-green
  labels:
    app: capstone-app-green
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app-green
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app-green
    spec:
      containers:
        - image: andrecamilosr/capstone-app-green
          imagePullPolicy: Always
          name: capstone-app-green
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-green
  labels:
    app: capstone-app-green
spec:
  type: LoadBalancer
  selector:
    app: capstone-app-green
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP